name: "Main / Pull requests build"
on:
    workflow_dispatch:
    pull_request:
        paths-ignore:
            - '.txt'
            - 'LICENSE'
            - 'docs/**'
        branches: [ main ]
    push:
        branches:
            - main
            - master

jobs:
    pre-commit:
        name: Pre-commit check
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout git repository
                uses: actions/checkout@v4.1.6
            -   name: Setup python
                uses: actions/setup-python@v5
                with:
                    python-version: "3.9"
            -   uses: actions/setup-java@v4
                with:
                    distribution: 'temurin'
                    java-version: '23'
    build:
        runs-on: ${{ matrix.os }}
        needs: [ pre-commit ]
        strategy:
            fail-fast: true
            matrix:
                #os: [ windows-latest, ubuntu-latest, macos-13 ]
                os: [ ubuntu-latest ]
            max-parallel: 1
        steps:
            -   uses: actions/checkout@v4.1.6
            -   name: Set up JDK 23
                uses: actions/setup-java@v4.2.1
                with:
                    distribution: 'temurin'
                    java-version: 23
                    architecture: x64
                    cache: 'maven'
            - name: Cache Maven dependencies
              uses: actions/cache@v3
              with:
                path: ~/.m2/repository
                key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
                restore-keys: |
                  maven-${{ runner.os }}-
            
            -   name: Build with Maven
                run: mvn --no-transfer-progress verify
            -   name: Build and analyze
                env:
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=vchaudh3_webgoat-2707
        
